app.admin.username=admin
app.usuarios.franvazxc=tuanny
app.usuarios.wendyfv=wendy
app.usuarios.eli_torres16=eliziene
telegram.bot.token=860926911:AAFcJUKkP80YmHUc1x7nMSIkSpnBfpnbbw
telegram.bot.username=refin_clt_bot